### ISSUE TITLE
HTTP 206 Partial Content Error with WebDAV on Zotero

### ISSUE THREAD

**Issue by erbanku** [abersheeran/r2-webdav#4]
**Describe the bug**
When attempting to bind a WebDAV server to Zotero for file syncing, an HTTP 206 Partial Content error occurs, preventing successful binding and synchronization.

**To Reproduce**
1. Go to 'Zotero Preferences'
2. Click on 'Sync'
3. Set up WebDAV by entering the WebDAV server URL, username, and password
4. Click on 'Verify Server' to test the connection
5. See error

**Expected behavior**
A clear and concise description of what you expected to happen. The WebDAV server should bind successfully without errors, allowing for file synchronization with Zotero.

**Screenshots**
![image](https://github.com/abersheeran/r2-webdav/assets/79493862/f9de3699-3cda-4645-a92f-67450601d0c1)

**Comment by abersheeran** [comment]
If anyone can open a PR to address this issue, I'd be happy to review it. But since I haven't used this software, I can't test it.

**Comment by abersheeran** [comment]
@erbanku Can you test #9? If you confirm that the tests pass, I will merge it.

**Comment by erbanku** [comment]
> @erbanku Can you test #9? If you confirm that the tests pass, I will merge it.

Works perfectly. You can merge it now!

![image](https://github.com/user-attachments/assets/ea3ab7d3-5807-4710-b3ce-e086bfb80bb8)
